# Student Marks Analysis

In [ ]:
import numpy as np

marks = np.array([45, 78, 62, 90, 55])

# Average marks
print("Average Marks:", np.mean(marks))

# Highest and Lowest marks
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))

# Students above average
print("Students Above Average:", np.sum(marks > np.mean(marks)))

Average Marks: 66.0
Highest Marks: 90
Lowest Marks: 45
Students Above Average: 2


# Temperature Data

In [ ]:
import numpy as np

temp = np.array([30, 32, 35, 38, 33])

# Celsius to Fahrenheit
fahrenheit = (temp * 9/5) + 32
print("Temperature in Fahrenheit:", fahrenheit)

# Hottest and Coldest Day
print("Hottest Temperature:", np.max(temp))
print("Coldest Temperature:", np.min(temp))

# Days above 34°C
print("Days Above 34°C:", np.sum(temp > 34))

Temperature in Fahrenheit: [ 86.   89.6  95.  100.4  91.4]
Hottest Temperature: 38
Coldest Temperature: 30
Days Above 34°C: 2


# Sales Report

In [11]:
import numpy as np

sales = np.array([
    [200, 250, 300, 280, 260],
    [180, 220, 270, 260, 240],
    [210, 260, 310, 290, 270]
])

# Total sales of each shop
total_sales = np.sum(sales, axis=1)
print("Total Sales of Each Shop:")
print(total_sales)

# Shop with highest sales
print("Shop with Highest Sales:", np.argmax(total_sales) + 1)

# Average sales per day
print("Average Sales Per Day:")
print(np.mean(sales, axis=0))

Total Sales of Each Shop:
[1290 1170 1340]
Shop with Highest Sales: 3
Average Sales Per Day:
[196.66666667 243.33333333 293.33333333 276.66666667 256.66666667]


# Product Price Update

In [13]:
import numpy as np

prices = np.array([150, 450, 600, 800, 300], dtype=float)

# Add 10% Tax
prices = prices * 1.10

# Apply 20% discount on products above 500
prices[prices > 500] *= 0.80

print("Final Price List:")
print(prices)

Final Price List:
[165. 495. 528. 704. 330.]


# Attendance Tracker

In [12]:
import numpy as np

attendance = np.array([
    [1, 1, 1, 0, 1],
    [1, 0, 1, 1, 1],
    [0, 1, 1, 0, 1],
    [1, 1, 1, 1, 1],
    [1, 0, 0, 1, 1]
])

# Total attendance of each student
total = np.sum(attendance, axis=1)
print("Attendance of Each Student:")
print(total)

# Students with attendance below 4
print("Students Below 4 Days Attendance:")
print(np.where(total < 4)[0] + 1)

# Most regular student
print("Most Regular Student:", np.argmax(total) + 1)

Attendance of Each Student:
[4 4 3 5 3]
Students Below 4 Days Attendance:
[3 5]
Most Regular Student: 4
